name: CMake

on:
  push: { branches: [main, dev] }
  pull_request: { branches: [main, dev] }

env:
  BUILD_TYPE: Release

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install libusb-1.0-0-dev

      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

      - name: Build
        run: cmake --build build --config ${{ env.BUILD_TYPE }} -j

      - name: Test
        run: ctest --test-dir build --output-on-failure